on: [push, pull_request]
name: Code coverage
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lib --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: lcov.info
          flags: unit
          verbose: true
          fail_ci_if_error: true
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --test '*' --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: lcov.info
          flags: integration
          verbose: true
          fail_ci_if_error: true
